services:
  server:
    container_name: server
    image: denoland/deno:alpine
    ports:
      - 1993:1993
    volumes:
      - .:/app
      - ./.run/logs/server:/app/logs
    working_dir: /app
    environment:
      - PORT=1993
    command: run --allow-env --allow-net --watch ./src/main.ts
